// @ts-nocheck
// This file is generated by Umi automatically
// DO NOT CHANGE IT MANUALLY!
import favoriteMenu from './favoriteMenu';

export const models = {
    favoriteMenu: { namespace: 'favoriteMenu', model: favoriteMenu },
} as const
